### ISSUE TITLE
hypnos sleeps twice

### ISSUE THREAD

**Issue by yjh0502** [transitorykris/hypnos#1]
first sleep on:
https://github.com/transitorykris/hypnos/blob/master/hypnos.go#L21

second sleep on:
https://github.com/transitorykris/hypnos/blob/master/cmd/hypnos/main.go#L55

It seems that first sleep should be removed.

**Comment by transitorykris** [comment]
Oh wow, that is not right. Fixed! hypnos.Sleep() no longer sleeps, that should be up to the client.
